import AppKit
import Combine
import QuickLookThumbnailing
import UniformTypeIdentifiers

/// Watches the system pasteboard and keeps a short rolling history of what you
/// copied — now including **images and files (images, videos, any document)**,
/// not just text. Each entry can be clicked to restore it to the clipboard so
/// you can paste it again, including attaching images/videos elsewhere.
///
/// Privacy: clips marked transient or concealed (password managers, OTP
/// fields) are ignored, and nothing is persisted to disk — history lives in
/// memory only and clears on quit.
///
/// Main-actor isolated: the poll timer runs on the main run loop and every
/// consumer is a SwiftUI view, the hub, or the notch view model.
@MainActor
final class ClipboardService: ObservableObject {

    struct Clip: Identifiable, Equatable {
        let id: UUID
        let kind: Kind
        let date: Date

        enum Kind: Equatable {
            case text(String)
            case image(Data) // PNG-encoded bitmap copied directly (e.g. screenshots)
            case file(URL) // a file copied in Finder — images, videos, anything
        }

        /// One-line label for the entry.
        var preview: String {
            switch kind {
            case .text(let text):
                let line = text.replacingOccurrences(of: "\n", with: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                return line.isEmpty ? "Empty text" : line
            case .image:
                return "Image"
            case .file(let url):
                return url.lastPathComponent
            }
        }

        var symbol: String {
            switch kind {
            case .text: "doc.text"
            case .image: "photo"
            case .file(let url): Clip.symbol(for: url)
            }
        }

        var isVisual: Bool {
            switch kind {
            case .text: false
            case .image, .file: true
            }
        }

        private static func symbol(for url: URL) -> String {
            guard let type = UTType(filenameExtension: url.pathExtension) else { return "doc" }
            if type.conforms(to: .movie) || type.conforms(to: .video) { return "film" }
            if type.conforms(to: .image) { return "photo" }
            if type.conforms(to: .audio) { return "music.note" }
            return "doc"
        }
    }

    @Published private(set) var clips: [Clip] = []
    /// Lazily-generated thumbnails for image/file clips, keyed by clip id.
    @Published private(set) var thumbnails: [UUID: NSImage] = [:]

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private let historyLimit = 12

    /// How many ticks a change with nothing readable behind it is given before
    /// it is written off.
    static let maximumSampleRetries = 3
    private var retryingChangeCount: Int?
    private var retryAttempts = 0

    /// The pasteboard is injectable so tests can run against a private named
    /// pasteboard — a bare `ClipboardService()` in a test used to write its
    /// fixture strings straight onto the clipboard the user was working with.
    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    /// Pasteboard markers used by password managers / transient producers.
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    /// Fired when something NEW lands on the pasteboard — not when a history
    /// entry is restored via `copy(_:)`. The copy HUD hangs off this.
    var onCopy: ((Clip) -> Void)?

    func start() {
        guard timer == nil else { return }
        sample()
        // A quarter second, not one second: the tick is a single changeCount
        // integer compare until something is actually copied, and the copy HUD
        // should appear while the ⌘C is still in the user's fingers.
        let timer = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.sample() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Restore to clipboard

    /// The pasteboard's current generation. Compare a value taken from `copy`
    /// against this to find out whether anything has written since.
    var changeCount: Int { pasteboard.changeCount }

    /// Puts a history entry back on the pasteboard. History order is left
    /// alone: reordering under the pointer makes the next click land on a
    /// different clip than the one it appears to target.
    ///
    /// Returns the change count the write produced, so a caller about to
    /// synthesize a paste can check the clip is still the one on offer.
    @discardableResult
    func copy(_ clip: Clip) -> Int {
        pasteboard.clearContents()
        switch clip.kind {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data):
            if let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        case .file(let url):
            pasteboard.writeObjects([url as NSURL])
        }
        // Don't re-ingest our own write on the next tick.
        lastChangeCount = pasteboard.changeCount
        clearRetry()
        return lastChangeCount
    }

    func clear() {
        clips.removeAll()
        thumbnails.removeAll()
    }

    // MARK: - Sampling

    /// Internal so tests can drive a tick without waiting on the timer.
    func sample() {
        // Read the counter once. Reading it again to store it opens a window
        // where a copy that landed in between is marked as already seen.
        let observed = pasteboard.changeCount
        guard observed != lastChangeCount else { return }

        if hasIgnoredMarkers() {
            lastChangeCount = observed
            clearRetry()
            return
        }

        let captured = readCurrentContent()

        // Ask again. Writing to the pasteboard is several calls — clear it,
        // declare the types, set the data — and the privacy markers are not
        // necessarily there when the content is. Sampling in the middle of a
        // password manager's write could read the secret before the marker
        // saying not to arrived.
        if hasIgnoredMarkers() {
            lastChangeCount = observed
            clearRetry()
            return
        }

        guard !captured.isEmpty else {
            // `clearContents()` bumps the counter before the content it is
            // clearing the way for exists. Marking this generation as seen
            // would drop the copy entirely: the user copies something, it
            // never enters the history, and the next paste from the notch is
            // whatever came before it. Leave the counter alone and look again
            // on the next tick — but not forever, or a genuinely empty
            // pasteboard would be re-read four times a second all session.
            noteEmptyRead(of: observed)
            return
        }

        lastChangeCount = observed
        clearRetry()
        add(contentsOf: captured)
    }

    /// Markers used by password managers and transient producers.
    private func hasIgnoredMarkers() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { ignoredTypes.contains($0.rawValue) }
    }

    /// Priority: real files (covers images/videos) › raw image › text.
    private func readCurrentContent() -> [Clip.Kind] {
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return urls.prefix(4).map { .file($0) }
        }

        if let image = NSImage(pasteboard: pasteboard), let data = image.pngData {
            return [.image(data)]
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return [.text(text)]
        }

        return []
    }

    private func noteEmptyRead(of changeCount: Int) {
        guard retryingChangeCount == changeCount else {
            retryingChangeCount = changeCount
            retryAttempts = 1
            return
        }
        retryAttempts += 1
        guard retryAttempts >= Self.maximumSampleRetries else { return }
        lastChangeCount = changeCount
        clearRetry()
    }

    private func clearRetry() {
        retryingChangeCount = nil
        retryAttempts = 0
    }

    // MARK: - History management

    /// Records newly-copied content at the head of the history. Internal rather
    /// than private so tests can seed history without driving the real
    /// pasteboard.
    func add(_ kind: Clip.Kind) {
        add(contentsOf: [kind])
    }

    /// Records one copy that carried several items — selecting four files in
    /// Finder and pressing ⌘C is a single gesture.
    ///
    /// Inserted back to front so the history reads in the order they were
    /// selected, and announced once: adding them one at a time reversed them
    /// and raised the copy popup once per file.
    func add(contentsOf kinds: [Clip.Kind]) {
        guard !kinds.isEmpty else { return }
        for kind in kinds.reversed() {
            removeClips { $0.kind == kind }
            let clip = Clip(id: UUID(), kind: kind, date: Date())
            clips.insert(clip, at: 0)
            generateThumbnail(for: clip)
        }
        trim()
        if let newest = clips.first { onCopy?(newest) }
    }

    /// Drops clips and their thumbnails together — a clip removed without its
    /// thumbnail leaks an entry keyed by an id nothing renders any more.
    private func removeClips(where shouldRemove: (Clip) -> Bool) {
        for clip in clips where shouldRemove(clip) { thumbnails[clip.id] = nil }
        clips.removeAll(where: shouldRemove)
    }

    private func trim() {
        guard clips.count > historyLimit else { return }
        for clip in clips[historyLimit...] { thumbnails[clip.id] = nil }
        clips = Array(clips.prefix(historyLimit))
    }

    // MARK: - Thumbnails

    /// Whether the file can be read without macOS raising a folder-permission
    /// dialog.
    ///
    /// With Full Disk Access there is nothing to avoid. Without it, the
    /// protected locations are the ones worth stepping around — the user's
    /// Desktop, Documents, Downloads, and iCloud Drive. Anywhere else (a temp
    /// directory, an external volume, the app's own container) reads freely.
    private func isReadableWithoutPrompting(_ url: URL) -> Bool {
        guard !FullDiskAccess.isGranted() else { return true }

        let home = URL(fileURLWithPath: NSHomeDirectory()).standardizedFileURL.path
        let guarded = ["Desktop", "Documents", "Downloads", "Library/Mobile Documents"]
            .map { home + "/" + $0 }
        let path = url.standardizedFileURL.path
        return !guarded.contains { path == $0 || path.hasPrefix($0 + "/") }
    }

    private func generateThumbnail(for clip: Clip) {
        switch clip.kind {
        case .text:
            break
        case .image(let data):
            if let image = NSImage(data: data) {
                thumbnails[clip.id] = image
            }
        case .file(let url):
            generateFileThumbnail(url, id: clip.id)
        }
    }

    private func generateFileThumbnail(_ url: URL, id: UUID) {
        // QuickLook reads the file, which is exactly what makes macOS put up a
        // "NotchHub would like to access files in your Desktop folder" dialog —
        // once per protected folder, unprompted, just because something was
        // copied. If the file sits somewhere protected and the app has not been
        // granted Full Disk Access, skip the thumbnail rather than trigger that:
        // the popup already has the file's icon, and a thumbnail is not worth
        // interrupting the user to ask for.
        guard isReadableWithoutPrompting(url) else { return }

        let scale = NSScreen.main?.backingScaleFactor ?? 2
        let request = QLThumbnailGenerator.Request(
            fileAt: url,
            size: CGSize(width: 72, height: 72),
            scale: scale,
            representationTypes: .thumbnail
        )
        QLThumbnailGenerator.shared.generateBestRepresentation(for: request) { [weak self] rep, _ in
            guard let rep else { return }
            let image = rep.nsImage
            Task { @MainActor [weak self] in
                // Only keep it if the clip is still in history.
                guard let self, self.clips.contains(where: { $0.id == id }) else { return }
                self.thumbnails[id] = image
            }
        }
    }
}

private extension NSImage {
    /// PNG encoding for compact in-memory storage of copied bitmaps.
    var pngData: Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
