import AppKit
import Combine
import QuickLookThumbnailing
import UniformTypeIdentifiers

/// Watches the system pasteboard and keeps a short rolling history of what you
/// copied — now including **images and files (images, videos, any document)**,
/// not just text. Each entry can be clicked to restore it to the clipboard so
/// you can paste it again, including attaching images/videos elsewhere.
///
/// Privacy: clips marked transient or concealed (password managers, OTP
/// fields) are ignored, and nothing is persisted to disk — history lives in
/// memory only and clears on quit.
///
/// Main-actor isolated: the poll timer runs on the main run loop and every
/// consumer is a SwiftUI view, the hub, or the notch view model.
@MainActor
final class ClipboardService: ObservableObject {

    struct Clip: Identifiable, Equatable {
        let id: UUID
        let kind: Kind
        let date: Date

        enum Kind: Equatable {
            case text(String)
            case image(Data) // PNG-encoded bitmap copied directly (e.g. screenshots)
            case file(URL) // a file copied in Finder — images, videos, anything
        }

        /// One-line label for the entry.
        var preview: String {
            switch kind {
            case .text(let text):
                let line = text.replacingOccurrences(of: "\n", with: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                return line.isEmpty ? "Empty text" : line
            case .image:
                return "Image"
            case .file(let url):
                return url.lastPathComponent
            }
        }

        var symbol: String {
            switch kind {
            case .text: "doc.text"
            case .image: "photo"
            case .file(let url): Clip.symbol(for: url)
            }
        }

        var isVisual: Bool {
            switch kind {
            case .text: false
            case .image, .file: true
            }
        }

        private static func symbol(for url: URL) -> String {
            guard let type = UTType(filenameExtension: url.pathExtension) else { return "doc" }
            if type.conforms(to: .movie) || type.conforms(to: .video) { return "film" }
            if type.conforms(to: .image) { return "photo" }
            if type.conforms(to: .audio) { return "music.note" }
            return "doc"
        }
    }

    @Published private(set) var clips: [Clip] = []
    /// Lazily-generated thumbnails for image/file clips, keyed by clip id.
    @Published private(set) var thumbnails: [UUID: NSImage] = [:]

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let historyLimit = 12

    /// Pasteboard markers used by password managers / transient producers.
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    /// Fired when something NEW lands on the pasteboard — not when a history
    /// entry is restored via `copy(_:)`. The copy HUD hangs off this.
    var onCopy: ((Clip) -> Void)?

    func start() {
        guard timer == nil else { return }
        sample()
        // A quarter second, not one second: the tick is a single changeCount
        // integer compare until something is actually copied, and the copy HUD
        // should appear while the ⌘C is still in the user's fingers.
        let timer = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.sample() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Restore to clipboard

    func copy(_ clip: Clip) {
        pasteboard.clearContents()
        switch clip.kind {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data):
            if let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        case .file(let url):
            pasteboard.writeObjects([url as NSURL])
        }
        // Don't re-ingest our own write on the next tick.
        lastChangeCount = pasteboard.changeCount
        promote(clip)
    }

    func clear() {
        clips.removeAll()
        thumbnails.removeAll()
    }

    // MARK: - Sampling

    private func sample() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Respect privacy markers (passwords, OTPs, transient copies).
        if let types = pasteboard.types,
           types.contains(where: { ignoredTypes.contains($0.rawValue) }) {
            return
        }

        // Priority: real files (covers images/videos) › raw image › text.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            for url in urls.prefix(4) { add(.file(url)) }
            return
        }

        if let image = NSImage(pasteboard: pasteboard), let data = image.pngData {
            add(.image(data))
            return
        }

        if let text = pasteboard.string(forType: .string) {
            let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !cleaned.isEmpty else { return }
            add(.text(text))
        }
    }

    // MARK: - History management

    private func add(_ kind: Clip.Kind) {
        clips.removeAll { $0.kind == kind }
        let clip = Clip(id: UUID(), kind: kind, date: Date())
        clips.insert(clip, at: 0)
        trim()
        generateThumbnail(for: clip)
        onCopy?(clip)
    }

    private func promote(_ clip: Clip) {
        clips.removeAll { $0.kind == clip.kind }
        let fresh = Clip(id: UUID(), kind: clip.kind, date: Date())
        clips.insert(fresh, at: 0)
        trim()
        generateThumbnail(for: fresh)
    }

    private func trim() {
        guard clips.count > historyLimit else { return }
        for clip in clips[historyLimit...] { thumbnails[clip.id] = nil }
        clips = Array(clips.prefix(historyLimit))
    }

    // MARK: - Thumbnails

    /// Whether the file can be read without macOS raising a folder-permission
    /// dialog.
    ///
    /// With Full Disk Access there is nothing to avoid. Without it, the
    /// protected locations are the ones worth stepping around — the user's
    /// Desktop, Documents, Downloads, and iCloud Drive. Anywhere else (a temp
    /// directory, an external volume, the app's own container) reads freely.
    private func isReadableWithoutPrompting(_ url: URL) -> Bool {
        guard !FullDiskAccess.isGranted() else { return true }

        let home = URL(fileURLWithPath: NSHomeDirectory()).standardizedFileURL.path
        let guarded = ["Desktop", "Documents", "Downloads", "Library/Mobile Documents"]
            .map { home + "/" + $0 }
        let path = url.standardizedFileURL.path
        return !guarded.contains { path == $0 || path.hasPrefix($0 + "/") }
    }

    private func generateThumbnail(for clip: Clip) {
        switch clip.kind {
        case .text:
            break
        case .image(let data):
            if let image = NSImage(data: data) {
                thumbnails[clip.id] = image
            }
        case .file(let url):
            generateFileThumbnail(url, id: clip.id)
        }
    }

    private func generateFileThumbnail(_ url: URL, id: UUID) {
        // QuickLook reads the file, which is exactly what makes macOS put up a
        // "NotchHub would like to access files in your Desktop folder" dialog —
        // once per protected folder, unprompted, just because something was
        // copied. If the file sits somewhere protected and the app has not been
        // granted Full Disk Access, skip the thumbnail rather than trigger that:
        // the popup already has the file's icon, and a thumbnail is not worth
        // interrupting the user to ask for.
        guard isReadableWithoutPrompting(url) else { return }

        let scale = NSScreen.main?.backingScaleFactor ?? 2
        let request = QLThumbnailGenerator.Request(
            fileAt: url,
            size: CGSize(width: 72, height: 72),
            scale: scale,
            representationTypes: .thumbnail
        )
        QLThumbnailGenerator.shared.generateBestRepresentation(for: request) { [weak self] rep, _ in
            guard let rep else { return }
            let image = rep.nsImage
            Task { @MainActor [weak self] in
                // Only keep it if the clip is still in history.
                guard let self, self.clips.contains(where: { $0.id == id }) else { return }
                self.thumbnails[id] = image
            }
        }
    }
}

private extension NSImage {
    /// PNG encoding for compact in-memory storage of copied bitmaps.
    var pngData: Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
