import AppKit
import Combine
import QuickLookThumbnailing
import UniformTypeIdentifiers

/// Watches the system pasteboard and keeps a short rolling history of what you
/// copied — now including **images and files (images, videos, any document)**,
/// not just text. Each entry can be clicked to restore it to the clipboard so
/// you can paste it again, including attaching images/videos elsewhere.
///
/// Privacy: clips marked transient or concealed (password managers, OTP
/// fields) are ignored, and nothing is persisted to disk — history lives in
/// memory only and clears on quit.
final class ClipboardService: ObservableObject {

    struct Clip: Identifiable, Equatable {
        let id: UUID
        let kind: Kind
        let date: Date

        enum Kind: Equatable {
            case text(String)
            case image(Data) // PNG-encoded bitmap copied directly (e.g. screenshots)
            case file(URL) // a file copied in Finder — images, videos, anything
        }

        /// One-line label for the entry.
        var preview: String {
            switch kind {
            case .text(let t):
                let line = t.replacingOccurrences(of: "\n", with: " ")
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                return line.isEmpty ? "Empty text" : line
            case .image:
                return "Image"
            case .file(let url):
                return url.lastPathComponent
            }
        }

        var symbol: String {
            switch kind {
            case .text: "doc.text"
            case .image: "photo"
            case .file(let url): Clip.symbol(for: url)
            }
        }

        var isVisual: Bool {
            switch kind {
            case .text: false
            case .image, .file: true
            }
        }

        private static func symbol(for url: URL) -> String {
            guard let type = UTType(filenameExtension: url.pathExtension) else { return "doc" }
            if type.conforms(to: .movie) || type.conforms(to: .video) { return "film" }
            if type.conforms(to: .image) { return "photo" }
            if type.conforms(to: .audio) { return "music.note" }
            return "doc"
        }
    }

    @Published private(set) var clips: [Clip] = []
    /// Lazily-generated thumbnails for image/file clips, keyed by clip id.
    @Published private(set) var thumbnails: [UUID: NSImage] = [:]

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let historyLimit = 12

    /// Pasteboard markers used by password managers / transient producers.
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    func start() {
        guard timer == nil else { return }
        sample()
        let timer = Timer(timeInterval: 1.0, repeats: true) { [weak self] _ in
            self?.sample()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Restore to clipboard

    func copy(_ clip: Clip) {
        pasteboard.clearContents()
        switch clip.kind {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .image(let data):
            if let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        case .file(let url):
            pasteboard.writeObjects([url as NSURL])
        }
        // Don't re-ingest our own write on the next tick.
        lastChangeCount = pasteboard.changeCount
        promote(clip)
    }

    func clear() {
        clips.removeAll()
        thumbnails.removeAll()
    }

    // MARK: - Sampling

    private func sample() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Respect privacy markers (passwords, OTPs, transient copies).
        if let types = pasteboard.types,
           types.contains(where: { ignoredTypes.contains($0.rawValue) }) {
            return
        }

        // Priority: real files (covers images/videos) › raw image › text.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            for url in urls.prefix(4) { add(.file(url)) }
            return
        }

        if let image = NSImage(pasteboard: pasteboard), let data = image.pngData {
            add(.image(data))
            return
        }

        if let text = pasteboard.string(forType: .string) {
            let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !cleaned.isEmpty else { return }
            add(.text(text))
        }
    }

    // MARK: - History management

    private func add(_ kind: Clip.Kind) {
        clips.removeAll { $0.kind == kind }
        let clip = Clip(id: UUID(), kind: kind, date: Date())
        clips.insert(clip, at: 0)
        trim()
        generateThumbnail(for: clip)
    }

    private func promote(_ clip: Clip) {
        clips.removeAll { $0.kind == clip.kind }
        let fresh = Clip(id: UUID(), kind: clip.kind, date: Date())
        clips.insert(fresh, at: 0)
        trim()
        generateThumbnail(for: fresh)
    }

    private func trim() {
        guard clips.count > historyLimit else { return }
        for clip in clips[historyLimit...] { thumbnails[clip.id] = nil }
        clips = Array(clips.prefix(historyLimit))
    }

    // MARK: - Thumbnails

    private func generateThumbnail(for clip: Clip) {
        switch clip.kind {
        case .text:
            break
        case .image(let data):
            if let image = NSImage(data: data) {
                thumbnails[clip.id] = image
            }
        case .file(let url):
            generateFileThumbnail(url, id: clip.id)
        }
    }

    private func generateFileThumbnail(_ url: URL, id: UUID) {
        let scale = NSScreen.main?.backingScaleFactor ?? 2
        let request = QLThumbnailGenerator.Request(
            fileAt: url,
            size: CGSize(width: 72, height: 72),
            scale: scale,
            representationTypes: .thumbnail
        )
        QLThumbnailGenerator.shared.generateBestRepresentation(for: request) { [weak self] rep, _ in
            guard let rep else { return }
            let image = rep.nsImage
            DispatchQueue.main.async {
                // Only keep it if the clip is still in history.
                guard let self, self.clips.contains(where: { $0.id == id }) else { return }
                self.thumbnails[id] = image
            }
        }
    }
}

private extension NSImage {
    /// PNG encoding for compact in-memory storage of copied bitmaps.
    var pngData: Data? {
        guard let tiff = tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
