#!/usr/bin/env python3
"""Convert Purge's explanations.json into NotchHub's CacheCatalog tables.

Usage: scripts/generate-cache-catalog.py <path/to/explanations.json> [<upstream commit>]

Writes Sources/NotchHub/Core/CacheCatalog+Apps.swift and
Sources/NotchHub/Core/CacheCatalog+DevTools.swift. Only the fields the
classifier needs are kept — key, display name, tag, aliases, bundle IDs and
scope; the prose explanations are dropped. The source catalog is MIT-licensed
(Jithin Sabu, https://github.com/jithin-sabu/purge-app); see
Vendor/purge-app/LICENSE and ACKNOWLEDGMENTS.md.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = os.path.join(ROOT, "Sources", "NotchHub", "Core")
MAX_WIDTH = 120

LEVELS = {"safe": ".safe", "medium": ".medium"}
SCOPES = {"app_caches": ".appCaches", "dev_tools": ".devTools"}


def swift_string(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def swift_array(values, prefix_width, indent=None):
    """An array literal, wrapped onto continuation lines when it is long.

    `prefix_width` is how many characters already sit on the line before the
    opening bracket; `indent` is the column continuation lines start at.
    """
    if indent is None:
        indent = prefix_width
    items = [swift_string(v) for v in values]
    one_line = "[" + ", ".join(items) + "]"
    if len(one_line) + prefix_width + 2 <= MAX_WIDTH:
        return one_line
    pad = " " * indent
    lines = ["["]
    current = pad + "    "
    for index, item in enumerate(items):
        separator = "," if index < len(items) - 1 else ""
        candidate = current + item + separator
        if len(candidate) > MAX_WIDTH and current.strip():
            lines.append(current.rstrip())
            current = pad + "    " + item + separator
        else:
            current = candidate
        current += " "
    lines.append(current.rstrip())
    lines.append(pad + "]")
    return "\n".join(lines)


def render_entry(entry):
    head = (
        f'        entry({swift_string(entry["key"])}, {swift_string(entry["display_name"])}, '
        f'{LEVELS[entry["tag"]]}, {SCOPES[entry["scope"]]}'
    )
    aliases = [a for a in entry.get("aliases", []) if a]
    bundle_ids = [b for b in entry.get("bundle_ids", []) if b]
    parts = []
    if aliases:
        parts.append(("aliases", aliases))
    if bundle_ids:
        parts.append(("bundleIDs", bundle_ids))
    if len(head) > MAX_WIDTH - 2:
        head = (
            f'        entry({swift_string(entry["key"])},\n'
            f'              {swift_string(entry["display_name"])}, {LEVELS[entry["tag"]]}, {SCOPES[entry["scope"]]}'
        )
    if not parts:
        return head + "),"
    one_line = head + ", " + ", ".join(f"{name}: {swift_array(values, 0)}" for name, values in parts) + "),"
    if len(one_line) <= MAX_WIDTH and "\n" not in one_line and "\n" not in head:
        return one_line
    lines = [head + ","]
    for index, (name, values) in enumerate(parts):
        suffix = "," if index < len(parts) - 1 else "),"
        lines.append(f"              {name}: {swift_array(values, 14 + len(name) + 2, 14)}{suffix}")
    return "\n".join(lines)


def render_file(name, entries, scope_label, commit):
    rendered = [render_entry(e) for e in entries]
    # SwiftLint's trailing_comma rule: the last element carries no comma.
    if rendered:
        rendered[-1] = rendered[-1].rstrip().removesuffix(",")
    body = "\n".join(rendered)
    return f"""// Generated by scripts/generate-cache-catalog.py — do not edit by hand.
//
// The {scope_label} half of the cache safety catalog, converted from Purge's
// explanations.json (https://github.com/jithin-sabu/purge-app, commit {commit[:12]}).
// Purge is © Jithin Sabu, MIT licensed; the license text is in
// Vendor/purge-app/LICENSE. Only the classification fields are kept — the
// per-entry prose was left behind because the notch has no room to show it.

extension CacheCatalog {{
    static let {name}: [Entry] = [
{body}
    ]
}}
"""


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8") as handle:
        catalog = json.load(handle)
    commit = sys.argv[2] if len(sys.argv) > 2 else "unknown"
    if not isinstance(catalog, list):
        sys.exit("expected a JSON array of catalog entries")
    seen = set()
    for entry in catalog:
        lowered = entry["key"].lower()
        if lowered in seen:
            sys.exit(f"duplicate key: {entry['key']}")
        seen.add(lowered)
        if entry["tag"] not in LEVELS:
            sys.exit(f"unknown tag {entry['tag']!r} on {entry['key']}")
        if entry["scope"] not in SCOPES:
            sys.exit(f"unknown scope {entry['scope']!r} on {entry['key']}")
    apps = [e for e in catalog if e["scope"] == "app_caches"]
    dev = [e for e in catalog if e["scope"] == "dev_tools"]
    outputs = {
        "CacheCatalog+Apps.swift": render_file("appEntries", apps, "app-cache", commit),
        "CacheCatalog+DevTools.swift": render_file("devToolEntries", dev, "developer-tool", commit),
    }
    for filename, text in outputs.items():
        path = os.path.join(CORE, filename)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
        print(f"wrote {os.path.relpath(path, ROOT)} ({text.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
